#####################################
# Site / Theme Configuration
#####################################
# Menu
menu:
  Home:
    Blog: /
    Archives: /archives
    Categories: /categories
    Tags: /tags
  Resources:
    "Recommended Books": /recommended-books
    "People to Follow": /recommended-people
    "Interviewing Resources": /interviewing-resources
    "Complete Software Career Info Guide": https://medium.com/static-void-academy/the-complete-software-career-information-guide-6d5b0d48e982
  "Software Roadmap":
    "Visual Roadmap": /software-roadmap
    "PDF Checklist": disabled
  "Online Academy": https://www.staticvoidacademy.com/
rss: /atom.xml

# Displayed in columns in footer
footer:
  Company:
    About: /about
    Credits: /credits
    Contact: /contact

# Default Keywords
keywords: blog, static, void, academy, program, programming, programmer, code, coding, coder, software, software engineer, develop, development, developer, python, javascript

# Put favicon.ico into theme source directory
favicon: favicon.ico

# {Font-Awesome-Icon}: {URL}
social:
  GitHub:
    url: https://github.com/Static-Void-Academy
    prefix: fab
  Youtube:
    url: https://www.youtube.com/channel/UCD9Vpco6dO5GfYOSmipwlvg
    prefix: fab
  Twitter:
    url: https://twitter.com/SV_Academy
    prefix: fab

# Only support Disqus currently
disqus_shortname: static-void-academy

# Google Stuff
google_site_verification:
google_analytics: UA-159047384-1

# Code Highlight theme
# Only theme available right now is darker
highlight_theme: darker
