#####################################
# Site / Theme Configuration
#####################################
# Menu
menu:
  Home: /
  Archives: archives
  Categories: categories
  Tags: tags
  About: about
rss: /atom.xml

# Default Keywords
keywords: blog, static, void, academy, program, programming, programmer, code, coding, coder, software, software engineer, develop, development, developer, python, javascript

# Put favicon.ico into theme source directory
favicon: favicon.ico

# {Font-Awesome-Icon}: {URL}
social:
  Graduation-Cap:
    url: https://sva.thinkific.com
    prefix: fas
  GitHub:
    url: https://github.com/Static-Void-Academy
    prefix: fab
  Youtube:
    url: https://www.youtube.com/channel/UCD9Vpco6dO5GfYOSmipwlvg
    prefix: fab
  Twitter:
    url: https://twitter.com/SV_Academy
    prefix: fab
  Medium:
    url: https://medium.com/static-void-academy
    prefix: fab

# Only support Disqus currently
disqus_shortname: static-void-academy

# Google Stuff
google_site_verification:
google_analytics: UA-159047384-1

